Add Anki package query required on Android 11
Fixes:

2021-10-01 22:03:51.933 21917-21917/se.whitchurch.nordict E/AndroidRuntime: FATAL EXCEPTION: main
    Process: se.whitchurch.nordict, PID: 21917
    java.lang.IllegalArgumentException: Unknown URL content://com.ichi2.anki.flashcards/models
        at android.content.ContentResolver.insert(ContentResolver.java:2172)
        at android.content.ContentResolver.insert(ContentResolver.java:2130)
        at com.ichi2.anki.api.AddContentApi.addNewCustomModel(AddContentApi.java:343)
        at se.whitchurch.nordict.Anki.getModelId(Anki.kt:33)
        at se.whitchurch.nordict.Anki.createCard(Anki.kt:57)
        at se.whitchurch.nordict.CardActivity.createCard(CardActivity.kt:62)
        at se.whitchurch.nordict.CardActivity.loadWord$lambda-7(CardActivity.kt:145)
        at se.whitchurch.nordict.CardActivity.$r8$lambda$ck4HBhEpPEx7Ykm6dZwzN57vlHQ(Unknown Source:0)
        at se.whitchurch.nordict.CardActivity$$ExternalSyntheticLambda3.onClick(Unknown Source:8)
        at android.view.View.performClick(View.java:7520)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1119)
        at android.view.View.performClickInternal(View.java:7489)
        at android.view.View.access$3600(View.java:826)
        at android.view.View$PerformClick.run(View.java:28555)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:8068)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)